### Site Settings ###
title               : Clément Delteil
description         : >-
                      <br>Hi there 👋, my name is <b>Clément Delteil</b>. I am a French computer science engineer with a focus on data science and artificial intelligence ⚡. 
                      <br>I am currently in Canada until June 2023 to complete my <b>double degree</b> ☃️.<br>
                      If you are interested in working with me or anything similar, then feel free to get in touch with me via any social network or e-mail 👀.<br>
                      I'm currently looking for a <b>challenging</b> Data Science / AI internship position 🤙.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
#repository          : Wazzabeee/Wazzabeee.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
#remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - documentation/*


### Author Info ###
author:
  name              : Clément Delteil
  image             : "assets/img/me_face.jpg"
  email             : clement.delteil@utbm.fr
  linkedin          : clementdelteil
  medium            : clementdelteil
  github            : Wazzabeee
  twitter           : clementdelteil_
  instagram         : clement_dltl


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  photography:
    output: true
    permalink: /photography/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-QGEQ1LTTSZ


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "photography"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
